name: CI - Playwright Tests (API + UI)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type: total | api | ui | login'
        required: true
        default: 'total'
      marker:
        description: 'Optional marker or suite (e.g. @smoke, @regression)'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables from secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
          echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          echo "BASE_URL_UI=${{ secrets.BASE_URL_UI }}" >> $GITHUB_ENV
          echo "MFA=${{ secrets.MFA }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" = "api" ]; then
            echo "Running API tests..."
            npm run test:api
          elif [ "${{ github.event.inputs.test_type }}" = "ui" ]; then
            echo "Running UI tests..."
            npm run test:ui
          elif [ "${{ github.event.inputs.test_type }}" = "login" ]; then
            echo "Running Login UI tests..."
            npm run test:login
          else
            echo "Running all tests..."
            npm run test
          fi

          if [ -n "${{ github.event.inputs.marker }}" ]; then
            echo "Filtering with marker: ${{ github.event.inputs.marker }}"
            npx playwright test -g "${{ github.event.inputs.marker }}" --reporter=line,allure-playwright
          fi

      - name: Load previous test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_history: allure-history

      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/